;; Cognitive Primitives AtomSpace Encoding
;; Generated by CogML Hypergraph Encoding

;; Pattern 1
(ConceptNode "perception_agent")

(SensoryNode "perception_agent_state_0"
    (stv 0.900000 0.300000)
    (attribute "modality" "VISUAL")
    (attribute "depth" "SURFACE")
    (attribute "context" "LOCAL")
    (attribute "prime_factors" [2, 5])
    (attribute "dof" 1)
    (attribute "tensor_shape" (4, 3, 3, 100, 100))
)

(EvaluationLink
    (PredicateNode "has_state")
    (ListLink
        (ConceptNode "perception_agent")
        (ConceptNode "perception_agent_state_0")
    )
)

(SensoryNode "perception_agent_state_1"
    (stv 0.600000 0.400000)
    (attribute "modality" "AUDITORY")
    (attribute "depth" "SURFACE")
    (attribute "context" "LOCAL")
    (attribute "prime_factors" [2, 2, 3])
    (attribute "dof" 1)
    (attribute "tensor_shape" (4, 3, 3, 100, 100))
)

(EvaluationLink
    (PredicateNode "has_state")
    (ListLink
        (ConceptNode "perception_agent")
        (ConceptNode "perception_agent_state_1")
    )
)

;; Pattern 2
(ConceptNode "cognition_agent")

(ConceptNode "cognition_agent_state_0"
    (stv 0.700000 0.800000)
    (attribute "modality" "SYMBOLIC")
    (attribute "depth" "PRAGMATIC")
    (attribute "context" "GLOBAL")
    (attribute "prime_factors" [3, 3, 3])
    (attribute "dof" 1)
    (attribute "tensor_shape" (4, 3, 3, 100, 100))
)

(EvaluationLink
    (PredicateNode "has_state")
    (ListLink
        (ConceptNode "cognition_agent")
        (ConceptNode "cognition_agent_state_0")
    )
)

(ConceptNode "cognition_agent_state_1"
    (stv 0.800000 0.500000)
    (attribute "modality" "TEXTUAL")
    (attribute "depth" "SEMANTIC")
    (attribute "context" "TEMPORAL")
    (attribute "prime_factors" [3, 3, 3])
    (attribute "dof" 1)
    (attribute "tensor_shape" (4, 3, 3, 100, 100))
)

(EvaluationLink
    (PredicateNode "has_state")
    (ListLink
        (ConceptNode "cognition_agent")
        (ConceptNode "cognition_agent_state_1")
    )
)

